### ISSUE TITLE
Installation erros on Ubuntu

### ISSUE THREAD

**Issue by blukee** [clementfarabet/gfx.js#1]
trace:

Using https://raw.github.com/clementfarabet/gfx.js/master/gfx.js-scm-0.rockspec... switching to 'build' mode
Cloning into 'gfx.js'...
remote: Counting objects: 199, done.
remote: Compressing objects: 100% (136/136), done.
remote: Total 199 (delta 55), reused 179 (delta 54)
Receiving objects: 100% (199/199), 5.33 MiB | 471 KiB/s, done.
Resolving deltas: 100% (55/55), done.
ls
bin            img     lib       README.md  templates
clients            index.js    LICENSE   server.js
gfx.js-scm-0.rockspec  install.sh  package.json  static
sh install.sh
==> installing Node.js dependencies
install.sh: 4: install.sh: [[: not found
npm http GET https://registry.npmjs.org/express/3.1.0
npm http GET https://registry.npmjs.org/pty.js/0.2.2
npm http GET https://registry.npmjs.org/socket.io/0.9.13
npm http 304 https://registry.npmjs.org/express/3.1.0
npm http 304 https://registry.npmjs.org/socket.io/0.9.13
npm http 304 https://registry.npmjs.org/pty.js/0.2.2
npm http GET https://registry.npmjs.org/connect/2.7.2
npm http GET https://registry.npmjs.org/commander/0.6.1
npm http GET https://registry.npmjs.org/mkdirp/0.3.3
npm http GET https://registry.npmjs.org/range-parser/0.0.4
npm http GET https://registry.npmjs.org/buffer-crc32/0.1.1
npm http GET https://registry.npmjs.org/fresh/0.1.0
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/cookie/0.0.5
npm http GET https://registry.npmjs.org/methods/0.0.1
npm http GET https://registry.npmjs.org/send/0.1.0
npm http GET https://registry.npmjs.org/cookie-signature/0.0.1
npm http GET https://registry.npmjs.org/redis/0.7.3
npm http GET https://registry.npmjs.org/base64id/0.1.0
npm http GET https://registry.npmjs.org/policyfile/0.0.4
npm http GET https://registry.npmjs.org/socket.io-client/0.9.11
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/mkdirp/0.3.3
npm http 304 https://registry.npmjs.org/commander/0.6.1
npm http 304 https://registry.npmjs.org/range-parser/0.0.4
npm http 304 https://registry.npmjs.org/fresh/0.1.0
npm http 304 https://registry.npmjs.org/cookie/0.0.5
npm http 304 https://registry.npmjs.org/buffer-crc32/0.1.1
npm http 304 https://registry.npmjs.org/cookie-signature/0.0.1
npm http 304 https://registry.npmjs.org/send/0.1.0
npm http 304 https://registry.npmjs.org/methods/0.0.1
npm http 304 https://registry.npmjs.org/connect/2.7.2
npm http 304 https://registry.npmjs.org/base64id/0.1.0
npm http 304 https://registry.npmjs.org/redis/0.7.3
npm http 304 https://registry.npmjs.org/policyfile/0.0.4
npm http 304 https://registry.npmjs.org/socket.io-client/0.9.11

> pty.js@0.2.2 install /tmp/luarocks_gfx.js-scm-0-3036/gfx.js/node_modules/pty.js
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
gyp ERR! stack     at install (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:65:16)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install](/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at getNodeDir (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:150:20)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:93:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:719:7)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:107:17)
gyp ERR! stack     at maybeClose (child_process.js:991:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:1141:11)
gyp ERR! stack     at Socket.EventEmitter.emit (events.js:104:17)
gyp ERR! stack     at Pipe.close (net.js:467:12)
gyp ERR! System Linux 3.8.0-37-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/luarocks_gfx.js-scm-0-3036/gfx.js/node_modules/pty.js
gyp ERR! node -v v0.11.13-pre
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm http GET https://registry.npmjs.org/mime/1.2.6
npm http 304 https://registry.npmjs.org/mime/1.2.6
npm ERR! pty.js@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.2 install script.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.8.0-37-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /tmp/luarocks_gfx.js-scm-0-3036/gfx.js
npm ERR! node -v v0.11.13-pre
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm http GET https://registry.npmjs.org/qs/0.5.1
npm http GET https://registry.npmjs.org/formidable/1.0.11
npm http GET https://registry.npmjs.org/pause/0.0.1
npm http GET https://registry.npmjs.org/bytes/0.1.0
npm http 304 https://registry.npmjs.org/formidable/1.0.11
npm http 304 https://registry.npmjs.org/pause/0.0.1
npm http 304 https://registry.npmjs.org/bytes/0.1.0
npm http 304 https://registry.npmjs.org/qs/0.5.1
npm http GET https://registry.npmjs.org/uglify-js/1.2.5
npm http GET https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http GET https://registry.npmjs.org/ws
npm http GET https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http 304 https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http 304 https://registry.npmjs.org/uglify-js/1.2.5
npm http 304 https://registry.npmjs.org/ws
npm http 304 https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http GET https://registry.npmjs.org/zeparser/0.0.5
npm http 304 https://registry.npmjs.org/zeparser/0.0.5
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/options
npm http GET https://registry.npmjs.org/tinycolor
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/tinycolor
npm http 304 https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/commander

> ws@0.4.31 install /tmp/luarocks_gfx.js-scm-0-3036/gfx.js/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /tmp/luarocks_gfx.js-scm-0-3036/gfx.js/npm-debug.log
npm ERR! not ok code 0
==> installing static resources into ~/.gfx.js/
install.sh: 15: install.sh: [[: not found
==> installing torch client into /usr/local/bin/../share/lua/5.1/gfx/
==> Torch client installed globally, run me like this:
$ torch -lgfx.start
or
$ torch -lgfx.go
(this will start the gfx server automatically)
Warning: Directory 'doc' not found
Updating manifest for /usr/local/lib/luarocks/rocks

gfx.js scm-0 is now built and installed in /usr/local/ (license: MIT)

**Comment by soumith** [comment]
did you use sudo for ubuntu? remember that /usr/local is not standard writeable on Ubuntu unlike OSX

**Comment by clementfarabet** [comment]
It seems that it's not recognizing the [[ in the install script. I was using sh in the rock install directive, which probably defaults to bash in 99% envs, but not this time. I've patched the rock, to use bash explicitly. Can you try to install again?

**Comment by blukee** [comment]
[[ Not found error is gone:

But still failed the build:

Using https://raw.github.com/clementfarabet/gfx.js/master/gfx.js-scm-0.rockspec... switching to 'build' mode
Cloning into 'gfx.js'...
remote: Counting objects: 199, done.
remote: Compressing objects: 100% (136/136), done.
remote: Total 199 (delta 55), reused 180 (delta 54)
Receiving objects: 100% (199/199), 5.33 MiB | 638 KiB/s, done.
Resolving deltas: 100% (55/55), done.
ls
bin            img     lib       README.md  templates
clients            index.js    LICENSE   server.js
gfx.js-scm-0.rockspec  install.sh  package.json  static
bash install.sh
==> installing Node.js dependencies
npm http GET https://registry.npmjs.org/pty.js/0.2.2
npm http GET https://registry.npmjs.org/socket.io/0.9.13
npm http GET https://registry.npmjs.org/express/3.1.0
npm http 304 https://registry.npmjs.org/express/3.1.0
npm http 304 https://registry.npmjs.org/socket.io/0.9.13
npm http 304 https://registry.npmjs.org/pty.js/0.2.2
npm http GET https://registry.npmjs.org/range-parser/0.0.4
npm http GET https://registry.npmjs.org/commander/0.6.1
npm http GET https://registry.npmjs.org/connect/2.7.2
npm http GET https://registry.npmjs.org/mkdirp/0.3.3
npm http GET https://registry.npmjs.org/cookie/0.0.5
npm http GET https://registry.npmjs.org/buffer-crc32/0.1.1
npm http GET https://registry.npmjs.org/fresh/0.1.0
npm http GET https://registry.npmjs.org/methods/0.0.1
npm http GET https://registry.npmjs.org/send/0.1.0
npm http GET https://registry.npmjs.org/cookie-signature/0.0.1
npm http GET https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/policyfile/0.0.4
npm http GET https://registry.npmjs.org/base64id/0.1.0
npm http GET https://registry.npmjs.org/redis/0.7.3
npm http GET https://registry.npmjs.org/socket.io-client/0.9.11
npm http 304 https://registry.npmjs.org/methods/0.0.1
npm http 304 https://registry.npmjs.org/commander/0.6.1
npm http 304 https://registry.npmjs.org/range-parser/0.0.4
npm http 304 https://registry.npmjs.org/buffer-crc32/0.1.1
npm http 304 https://registry.npmjs.org/cookie/0.0.5
npm http 304 https://registry.npmjs.org/cookie-signature/0.0.1
npm http 304 https://registry.npmjs.org/fresh/0.1.0

> pty.js@0.2.2 install /tmp/luarocks_gfx.js-scm-0-5455/gfx.js/node_modules/pty.js
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
gyp ERR! stack     at install (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:65:16)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install](/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at getNodeDir (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:150:20)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:93:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:719:7)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:107:17)
gyp ERR! stack     at maybeClose (child_process.js:991:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:1141:11)
gyp ERR! stack     at Socket.EventEmitter.emit (events.js:104:17)
gyp ERR! stack     at Pipe.close (net.js:467:12)
gyp ERR! System Linux 3.8.0-37-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/luarocks_gfx.js-scm-0-5455/gfx.js/node_modules/pty.js
gyp ERR! node -v v0.11.13-pre
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm http 304 https://registry.npmjs.org/redis/0.7.3
npm http 304 https://registry.npmjs.org/policyfile/0.0.4
npm http 304 https://registry.npmjs.org/base64id/0.1.0
npm http 304 https://registry.npmjs.org/connect/2.7.2
npm http 304 https://registry.npmjs.org/mkdirp/0.3.3
npm http 304 https://registry.npmjs.org/send/0.1.0
npm http 304 https://registry.npmjs.org/socket.io-client/0.9.11
npm ERR! pty.js@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.2 install script.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.8.0-37-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /tmp/luarocks_gfx.js-scm-0-5455/gfx.js
npm ERR! node -v v0.11.13-pre
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm http GET https://registry.npmjs.org/mime/1.2.6
npm http 304 https://registry.npmjs.org/mime/1.2.6
npm http GET https://registry.npmjs.org/qs/0.5.1
npm http GET https://registry.npmjs.org/formidable/1.0.11
npm http GET https://registry.npmjs.org/bytes/0.1.0
npm http GET https://registry.npmjs.org/pause/0.0.1
npm http 304 https://registry.npmjs.org/formidable/1.0.11
npm http 304 https://registry.npmjs.org/pause/0.0.1
npm http 304 https://registry.npmjs.org/qs/0.5.1
npm http 304 https://registry.npmjs.org/bytes/0.1.0
npm http GET https://registry.npmjs.org/uglify-js/1.2.5
npm http GET https://registry.npmjs.org/ws
npm http GET https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http GET https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http 304 https://registry.npmjs.org/uglify-js/1.2.5
npm http 304 https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http 304 https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http 304 https://registry.npmjs.org/ws
npm http GET https://registry.npmjs.org/zeparser/0.0.5
npm http 304 https://registry.npmjs.org/zeparser/0.0.5
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/tinycolor
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/tinycolor
npm http 304 https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/commander

> ws@0.4.31 install /tmp/luarocks_gfx.js-scm-0-5455/gfx.js/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /tmp/luarocks_gfx.js-scm-0-5455/gfx.js/npm-debug.log
npm ERR! not ok code 0
==> installing static resources into ~/.gfx.js/
==> installing torch client into /usr/local/bin/../share/lua/5.1/gfx/
==> Torch client installed globally, run me like this:
$ torch -lgfx.start
or
$ torch -lgfx.go
(this will start the gfx server automatically)
Warning: Directory 'doc' not found
Updating manifest for /usr/local/lib/luarocks/rocks

gfx.js scm-0 is now built and installed in /usr/local/ (license: MIT)

**Comment by blukee** [comment]
Yes. I used sudo

**Comment by danielhers** [comment]
I'm also getting this error. I didn't use sudo because I installed Node to a user directory (I don't have the superuser password). How do I provide the nodedir parameter so that I can tell it where my Node source directory is?

**Comment by iratus1** [comment]
I get same problem here ! I think that the problem is on gfx.js somewhere

**Comment by dtmoodie** [comment]
I too have what seems to be this issue. Using node 0.10.25, node-gyp 0.10.10.

Using https://raw.github.com/clementfarabet/gfx.js/master/gfx.js-scm-0.rockspec... switching to 'build' mode
Cloning into 'gfx.js'...
remote: Counting objects: 231, done.
remote: Compressing objects: 100% (164/164), done.
remote: Total 231 (delta 59), reused 210 (delta 56)
Receiving objects: 100% (231/231), 5.35 MiB | 2.79 MiB/s, done.
Resolving deltas: 100% (59/59), done.
Checking connectivity... done.
ls
bin  gfx.js-scm-0.rockspec  index.js       install.sh  LICENSE       README.md  static
clients  img            install-python.sh  lib         package.json  server.js  templates
bash install.sh
==> installing Node.js dependencies
npm http GET https://registry.npmjs.org/pty.js/0.2.4
npm http GET https://registry.npmjs.org/fsevents/0.2.0
npm http GET https://registry.npmjs.org/recursive-readdir/0.0.2
npm http GET https://registry.npmjs.org/express/3.4.4
npm http GET https://registry.npmjs.org/socket.io/0.9.16
npm http 304 https://registry.npmjs.org/express/3.4.4
npm http 304 https://registry.npmjs.org/fsevents/0.2.0
npm http 304 https://registry.npmjs.org/pty.js/0.2.4
npm http 304 https://registry.npmjs.org/recursive-readdir/0.0.2
npm http 304 https://registry.npmjs.org/socket.io/0.9.16
npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: fsevents@0.2.0
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! System Linux 3.13.0-30-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /tmp/luarocks_gfx.js-scm-0-3884/gfx.js
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code EBADPLATFORM
npm http GET https://registry.npmjs.org/connect/2.11.0
npm http GET https://registry.npmjs.org/commander/1.3.2
npm http GET https://registry.npmjs.org/mkdirp/0.3.5
npm http GET https://registry.npmjs.org/range-parser/0.0.4
npm http GET https://registry.npmjs.org/cookie/0.1.0
npm http GET https://registry.npmjs.org/fresh/0.2.0
npm http GET https://registry.npmjs.org/buffer-crc32/0.2.1
npm http GET https://registry.npmjs.org/methods/0.1.0
npm http GET https://registry.npmjs.org/send/0.1.4
npm http GET https://registry.npmjs.org/cookie-signature/1.0.1
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/socket.io-client/0.9.16
npm http GET https://registry.npmjs.org/policyfile/0.0.4
npm http GET https://registry.npmjs.org/redis/0.7.3
npm http GET https://registry.npmjs.org/base64id/0.1.0
npm http GET https://registry.npmjs.org/nan/0.7.0
npm http GET https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/mkdirp/0.3.5
npm http 304 https://registry.npmjs.org/range-parser/0.0.4
npm http 304 https://registry.npmjs.org/buffer-crc32/0.2.1
npm http 304 https://registry.npmjs.org/fresh/0.2.0
npm http 200 https://registry.npmjs.org/methods/0.1.0
npm http GET https://registry.npmjs.org/methods/-/methods-0.1.0.tgz
npm http 304 https://registry.npmjs.org/cookie-signature/1.0.1
npm http 304 https://registry.npmjs.org/send/0.1.4
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/socket.io-client/0.9.16
npm http 304 https://registry.npmjs.org/connect/2.11.0
npm http 304 https://registry.npmjs.org/policyfile/0.0.4
npm http 304 https://registry.npmjs.org/commander/1.3.2
npm http 304 https://registry.npmjs.org/cookie/0.1.0
npm http 200 https://registry.npmjs.org/methods/-/methods-0.1.0.tgz
npm http 304 https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/redis/0.7.3
npm http 304 https://registry.npmjs.org/base64id/0.1.0
npm http 304 https://registry.npmjs.org/nan/0.7.0
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/keypress
npm http GET https://registry.npmjs.org/ms/0.6.2

> pty.js@0.2.4 install /tmp/luarocks_gfx.js-scm-0-3884/gfx.js/node_modules/pty.js
> node-gyp rebuild

npm http GET https://registry.npmjs.org/qs/0.6.5
npm http GET https://registry.npmjs.org/bytes/0.2.1
npm http GET https://registry.npmjs.org/uid2/0.0.3
npm http GET https://registry.npmjs.org/methods/0.0.1
npm http GET https://registry.npmjs.org/pause/0.0.1
npm http 304 https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/raw-body/0.0.3
npm http GET https://registry.npmjs.org/negotiator/0.3.0
npm http GET https://registry.npmjs.org/multiparty/2.2.0
/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-30-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/luarocks_gfx.js-scm-0-3884/gfx.js/node_modules/pty.js
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm http 304 https://registry.npmjs.org/bytes/0.2.1
npm http 304 https://registry.npmjs.org/uid2/0.0.3
npm http GET https://registry.npmjs.org/uglify-js/1.2.5
npm http GET https://registry.npmjs.org/ws
npm http GET https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http GET https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http 304 https://registry.npmjs.org/keypress
npm http 304 https://registry.npmjs.org/pause/0.0.1
npm http 304 https://registry.npmjs.org/methods/0.0.1
npm http 304 https://registry.npmjs.org/raw-body/0.0.3
npm http 304 https://registry.npmjs.org/negotiator/0.3.0
npm http 304 https://registry.npmjs.org/ms/0.6.2
npm http 304 https://registry.npmjs.org/multiparty/2.2.0
npm http 304 https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http 304 https://registry.npmjs.org/ws
npm http 304 https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http 304 https://registry.npmjs.org/uglify-js/1.2.5
npm http GET https://registry.npmjs.org/zeparser/0.0.5
npm http 304 https://registry.npmjs.org/qs/0.6.5
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/tinycolor
npm http GET https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/zeparser/0.0.5
npm http 304 https://registry.npmjs.org/tinycolor
npm http 304 https://registry.npmjs.org/commander

> ws@0.4.31 install /tmp/luarocks_gfx.js-scm-0-3884/gfx.js/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/stream-counter
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/stream-counter
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/string_decoder
npm http 200 https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz
npm http 304 https://registry.npmjs.org/core-util-is
npm http 200 https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /tmp/luarocks_gfx.js-scm-0-3884/gfx.js/npm-debug.log
npm ERR! not ok code 0
==> installing static resources into ~/.gfx.js/
==> installing torch client into /usr/local/bin/../share/lua/5.1/gfx/
==> Torch client installed globally, run me like this:
$ luajit -lgfx.start
or
$ luajit -lgfx.go
(this will start the gfx server automatically)
gfx command-line binary installed. Use it to display images quickly
$ gfx test.jpg
Warning: Directory 'doc' not found
Updating manifest for /usr/local/lib/luarocks/rocks

gfx.js scm-0 is now built and installed in /usr/local/ (license: MIT)

**Comment by vchekan** [comment]
Any progress on this one?
I have similar issue on Linux Mint 17

# 

 ~/projects/torch7-gfx/gfx.js $ sudo luarocks make
ls
bin    clients            img   install-python.sh  lib      node_modules  README.md  static
build  gfx.js-scm-0.rockspec  index.js  install.sh     LICENSE  package.json  server.js  templates
bash install.sh
==> installing Node.js dependencies
npm http GET https://registry.npmjs.org/pty.js/0.2.4
npm http 304 https://registry.npmjs.org/pty.js/0.2.4
npm http GET https://registry.npmjs.org/nan/0.7.0
npm http GET https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/nan/0.7.0
npm http 304 https://registry.npmjs.org/extend

> pty.js@0.2.4 install /home/vadim/projects/torch7-gfx/gfx.js/node_modules/pty.js
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-29-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/vadim/projects/torch7-gfx/gfx.js/node_modules/pty.js
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! weird error 1
npm ERR! not ok code 0
==> installing static resources into ~/.gfx.js/
==> installing torch client into /usr/local/bin/../share/lua/5.1/gfx/
==> Torch client installed globally, run me like this:
$ luajit -lgfx.start
or
$ luajit -lgfx.go
(this will start the gfx server automatically)
gfx command-line binary installed. Use it to display images quickly
$ gfx test.jpg
Warning: Directory 'doc' not found
Updating manifest for /usr/local/lib/luarocks/rocks

gfx.js scm-0 is now built and installed in /usr/local/ (license: MIT)

**Comment by vchekan** [comment]
Solved on linux-mint (ubuntu)!

In debian-derived "node" is packaged as "nodejs". As result it will fail in many cases. I solved the problem by:

```
ln -s /usr/bin/nodejs /usr/bin/node
```

**Comment by abhishekraok** [comment]
Thanks vchekan, that linking helped me.
