### ISSUE TITLE
Another installation error in Ubuntu

### ISSUE THREAD

**Issue by iratus1** [clementfarabet/gfx.js#2]
I think that my problem is related to the already mention problem of installing gfx.js over ubuntu.

However I am posting the error message in case this may help somebody detect the problem.

Error message below:

```



==> installing Node.js dependencies
npm http GET https://registry.npmjs.org/pty.js/0.2.2
npm http GET https://registry.npmjs.org/socket.io/0.9.13
npm http GET https://registry.npmjs.org/express/3.1.0
npm http 304 https://registry.npmjs.org/express/3.1.0
npm http 304 https://registry.npmjs.org/pty.js/0.2.2
npm http 304 https://registry.npmjs.org/socket.io/0.9.13
npm http GET https://registry.npmjs.org/connect/2.7.2
npm http GET https://registry.npmjs.org/commander/0.6.1
npm http GET https://registry.npmjs.org/range-parser/0.0.4
npm http GET https://registry.npmjs.org/mkdirp/0.3.3
npm http GET https://registry.npmjs.org/buffer-crc32/0.1.1
npm http GET https://registry.npmjs.org/cookie/0.0.5
npm http GET https://registry.npmjs.org/fresh/0.1.0
npm http GET https://registry.npmjs.org/methods/0.0.1
npm http GET https://registry.npmjs.org/send/0.1.0
npm http GET https://registry.npmjs.org/cookie-signature/0.0.1
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/base64id/0.1.0
npm http GET https://registry.npmjs.org/socket.io-client/0.9.11
npm http GET https://registry.npmjs.org/policyfile/0.0.4
npm http GET https://registry.npmjs.org/redis/0.7.3
npm http 304 https://registry.npmjs.org/commander/0.6.1

> pty.js@0.2.2 install /tmp/luarocks_gfx.js-scm-0-1237/gfx.js/node_modules/pty.js
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
gyp ERR! stack     at install (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:65:16)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at getNodeDir (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:150:20)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:93:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:719:7)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:107:17)
gyp ERR! stack     at maybeClose (child_process.js:991:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:1141:11)
gyp ERR! stack     at Socket.EventEmitter.emit (events.js:104:17)
gyp ERR! stack     at Pipe.close (net.js:467:12)
gyp ERR! System Linux 3.11.0-19-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/luarocks_gfx.js-scm-0-1237/gfx.js/node_modules/pty.js
gyp ERR! node -v v0.11.13-pre
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm http 304 https://registry.npmjs.org/base64id/0.1.0
npm http 304 https://registry.npmjs.org/redis/0.7.3
npm http 304 https://registry.npmjs.org/buffer-crc32/0.1.1
npm http 304 https://registry.npmjs.org/range-parser/0.0.4
npm http 304 https://registry.npmjs.org/cookie/0.0.5
npm http 304 https://registry.npmjs.org/cookie-signature/0.0.1
npm http 304 https://registry.npmjs.org/methods/0.0.1
npm http 304 https://registry.npmjs.org/fresh/0.1.0
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/policyfile/0.0.4
npm http 304 https://registry.npmjs.org/mkdirp/0.3.3
npm http 304 https://registry.npmjs.org/send/0.1.0
npm http 304 https://registry.npmjs.org/connect/2.7.2
npm http 304 https://registry.npmjs.org/socket.io-client/0.9.11
npm ERR! pty.js@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.2 install script.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.11.0-19-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /tmp/luarocks_gfx.js-scm-0-1237/gfx.js
npm ERR! node -v v0.11.13-pre
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm http GET https://registry.npmjs.org/mime/1.2.6
npm http 304 https://registry.npmjs.org/mime/1.2.6
npm http GET https://registry.npmjs.org/qs/0.5.1
npm http GET https://registry.npmjs.org/formidable/1.0.11
npm http GET https://registry.npmjs.org/bytes/0.1.0
npm http GET https://registry.npmjs.org/pause/0.0.1
npm http 304 https://registry.npmjs.org/qs/0.5.1
npm http 304 https://registry.npmjs.org/pause/0.0.1
npm http GET https://registry.npmjs.org/uglify-js/1.2.5
npm http GET https://registry.npmjs.org/ws
npm http GET https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http GET https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http 304 https://registry.npmjs.org/formidable/1.0.11
npm http 304 https://registry.npmjs.org/bytes/0.1.0
npm http 304 https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http 304 https://registry.npmjs.org/uglify-js/1.2.5
npm http 304 https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http 304 https://registry.npmjs.org/ws
npm http GET https://registry.npmjs.org/zeparser/0.0.5
npm http 304 https://registry.npmjs.org/zeparser/0.0.5
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/tinycolor
npm http GET https://registry.npmjs.org/options
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/tinycolor

> ws@0.4.31 install /tmp/luarocks_gfx.js-scm-0-1237/gfx.js/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /tmp/luarocks_gfx.js-scm-0-1237/gfx.js/npm-debug.log
npm ERR! not ok code 0
==> installing static resources into ~/.gfx.js/
==> installing torch client into /usr/local/bin/../share/lua/5.1/gfx/
==> Torch client installed globally, run me like this:
$ torch -lgfx.start
or
$ torch -lgfx.go
(this will start the gfx server automatically)
Warning: Directory 'doc' not found
Updating manifest for /usr/local/lib/luarocks/rocks

gfx.js scm-0 is now built and installed in /usr/local/ (license: MIT)
```

**Comment by spk921** [comment]
I got simmilar error here 

```
 verbose linkBins pty.js@0.2.4                                                                                               
 verbose linkMans pty.js@0.2.4                                                                                               
 verbose rebuildBundles pty.js@0.2.4                                                                                         
 verbose rebuildBundles [ 'extend', 'nan' ]                                                                                  
 info install pty.js@0.2.4                                                                                                   
 verbose unsafe-perm in lifecycle true                                                                                       
 info pty.js@0.2.4 Failed to exec install script                                                                             
 verbose unlock done using /home/elab/.npm/_locks/pty-js-90e14bc554692913.lock for /home/elab/git/gfx.js/node_modules/pty.js 
 verbose stack Error: pty.js@0.2.4 install: `node-gyp rebuild`                                                               
 verbose stack Exit status 1                                                                                                 
 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)                     
 verbose stack     at emitTwo (events.js:87:13)                                                                              
 verbose stack     at EventEmitter.emit (events.js:172:7)                                                                    
 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)                          
 verbose stack     at emitTwo (events.js:87:13)                                                                              
 verbose stack     at ChildProcess.emit (events.js:172:7)                                                                    
 verbose stack     at maybeClose (internal/child_process.js:827:16)                                                          
 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)                                  
 verbose pkgid pty.js@0.2.4                                                                                                  
 verbose cwd /home/elab/git/gfx.js                                                                                           
 error Linux 4.2.0-27-generic                                                                                                
 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"                                                                       
 error node v4.4.4                                                                                                           
 error npm  v2.15.1                                                                                                          
 error code ELIFECYCLE                                                                                                       
 error pty.js@0.2.4 install: `node-gyp rebuild`                                                                              
 error Exit status 1                                                                                                         
 error Failed at the pty.js@0.2.4 install script 'node-gyp rebuild'.                                                         
 error This is most likely a problem with the pty.js package,                                                                
 error not with npm itself.                                                                                                  
 error Tell the author that this fails on your system:                                                                       
 error     node-gyp rebuild                                                                                                  
 error You can get information on how to open an issue for this project with:                                                
 error     npm bugs pty.js                                                                                                   
 error Or if that isn't available, you can get their info via:                                                               
 error                                                                                                                       
 error     npm owner ls pty.js                                                                                               
 error There is likely additional logging output above.                                                                      
 verbose exit [ 1, true ]                                                                                                    
 verbose unbuild node_modules/pty.js                                                                                         
 info preuninstall pty.js@0.2.4                                                                                              
 info uninstall pty.js@0.2.4                                                                                                 
 verbose unbuild rmStuff pty.js@0.2.4 from /home/elab/git/gfx.js/node_modules                                                
 info postuninstall pty.js@0.2.4                                                                                             
 silly gentlyRm /home/elab/git/gfx.js/node_modules/pty.js is being purged from base /home/elab/git/gfx.js                    
 verbose gentlyRm don't care about contents; nuking /home/elab/git/gfx.js/node_modules/pty.js                                
 silly vacuum-fs purging /home/elab/git/gfx.js/node_modules/pty.js                                                           
```
