### ISSUE TITLE
OSx 10.7.5 install error

### ISSUE THREAD

**Issue by skaae** [clementfarabet/gfx.js#22]
Following the installation instructions I get the following error when i execute

```
luarocks install https://raw.github.com/clementfarabet/gfx.js/master/gfx.js-scm-0.rockspec
```

```
Using https://raw.github.com/clementfarabet/gfx.js/master/gfx.js-scm-0.rockspec... switching to 'build' mode
Cloning into 'gfx.js'...
remote: Counting objects: 3215, done.
remote: Total 3215 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (3215/3215), 7.74 MiB | 515 KiB/s, done.
Resolving deltas: 100% (1439/1439), done.
mkdir: /usr/local/lib/luarocks/rocks/gfx.js/scm-0/lua: Permission denied
mkdir: /usr/local/lib/luarocks/rocks/gfx.js/scm-0/bin: Permission denied
mkdir: /usr/local/lib/luarocks/rocks/gfx.js/scm-0/conf: Permission denied
mkdir: /usr/local/lib/luarocks/rocks/gfx.js/scm-0/lib: Permission denied
ls
LICENSE         bin         gfx.js-scm-0.rockspec   index.js        install.sh      package.json        static
README.md       clients         img         install-python.sh   lib         server.js       templates
bash install.sh
==> installing Node.js dependencies

> fsevents@0.2.0 install /private/tmp/luarocks_gfx.js-scm-0-3945/gfx.js/node_modules/fsevents
> node-gyp rebuild

  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished

> pty.js@0.2.4 install /private/tmp/luarocks_gfx.js-scm-0-3945/gfx.js/node_modules/pty.js
> node-gyp rebuild

  CXX(target) Release/obj.target/pty/src/unix/pty.o
../src/unix/pty.cc:487:10: error: use of undeclared identifier 'openpty'
  return openpty(amaster, aslave, name, (termios *)termp, (winsize *)winp);
         ^
../src/unix/pty.cc:533:10: error: use of undeclared identifier 'forkpty'
  return forkpty(amaster, name, (termios *)termp, (winsize *)winp);
         ^
2 errors generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 11.4.2
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/tmp/luarocks_gfx.js-scm-0-3945/gfx.js/node_modules/pty.js
gyp ERR! node -v v0.10.30
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok 

> ws@0.4.32 install /private/tmp/luarocks_gfx.js-scm-0-3945/gfx.js/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
npm ERR! pty.js@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.4 install script.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 11.4.2
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /private/tmp/luarocks_gfx.js-scm-0-3945/gfx.js
npm ERR! node -v v0.10.30
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /private/tmp/luarocks_gfx.js-scm-0-3945/gfx.js/npm-debug.log
npm ERR! not ok code 0
==> installing static resources into ~/.gfx.js/
==> installing torch client into /usr/local/bin/../share/lua/5.1/gfx/
==> Torch client installed globally, run me like this:
$ luajit -lgfx.start
or
$ luajit -lgfx.go
(this will start the gfx server automatically)
gfx command-line binary installed. Use it to display images quickly
$ gfx test.jpg
Warning: Directory 'doc' not found
cp: /usr/local/lib/luarocks/rocks/gfx.js/scm-0/gfx.js-scm-0.rockspec: Permission denied
Updating manifest for /usr/local/lib/luarocks/rocks

gfx.js scm-0 is now built and installed in /usr/local/ (license: MIT)
```

I tried the various suggestions in 

https://github.com/clementfarabet/gfx.js/issues/17#issuecomment-47537686

Currently i get the following error when executing

```
 luajit -lgfx.go
```

```
luajit: /usr/local/share/lua/5.1/graphicsmagick/Image.lua:179: dlopen(libGraphicsMagickWand.dylib, 5): image not found
stack traceback:
    [C]: in function 'load'
    /usr/local/share/lua/5.1/graphicsmagick/Image.lua:179: in main chunk
    [C]: in function 'require'
    /usr/local/share/lua/5.1/graphicsmagick/init.lua:2: in main chunk
    [C]: in function 'require'
    /usr/local/share/lua/5.1/gfx/js.lua:9: in main chunk
    [C]: in function 'require'
    /usr/local/share/lua/5.1/gfx/go.lua:7: in main chunk
    [C]: at 0x010ae44260
    [C]: at 0x010ae1ae10
```

Any suggestions?

**Comment by soumith** [comment]
you need to install graphicsmagick on your system!
I think it is 

sudo apt-get install libgraphicsmagick-dev 

for ubuntu

**Comment by skaae** [comment]
I think I did. 

brew install graphicsmagick

**Comment by soumith** [comment]
In that case, can you verify that you have this file: /usr/local/lib/libGraphicsMagickWand.dylib

**Comment by skaae** [comment]
I have it

**Comment by soumith** [comment]
> dlopen(libGraphicsMagickWand.dylib, 5): image not found

I would suggest just removing imagemagick (brew remove imagemagick && brew cleanup) and installing it again, it is trying to find a certain version of graphicsmagick, and that happens to be a brew issue with imagemagick/graphicsmagick.

**Comment by vzhong** [comment]
@skaae I had the same problem on 10.10 and this took me quite a while to figure out:

Basically it seems like for whatever reason this dynamic library is not on the load path. Doing the following worked for me:

``` sh
export DYLD_FALLBACK_LIBRARY_PATH=/usr/local/lib/
```

**Comment by skaae** [comment]
Thanks. It works :) 
To sum up you need to follow the suggestion in 
https://github.com/clementfarabet/gfx.js/issues/17#issuecomment-47537686. Then `export DYLD_FALLBACK_LIBRARY_PATH=/usr/local/lib/` before you run  `th -lgfx.go`
