### ISSUE TITLE
Error in starting server

### ISSUE THREAD

**Issue by adityaarun1** [clementfarabet/gfx.js#27]
Hi,

I installed gfx.js as mentioned in the readme, but on starting the server as 
`$luajit -lgfx.start`
gives the following message and the server fails to start:
`[gfx.js] server started on port 8000, graphics will be rendered into http://localhost:8000`
`me@my-PC:~$` 
`module.js:340`
`throw err;`
`^`
`Error: Cannot find module '~/.gfx.js/server.js'`
`at Function.Module._resolveFilename (module.js:338:15)`
`at Function.Module._load (module.js:280:25)`
`at Function.Module.runMain (module.js:497:10)`
`at startup (node.js:119:16)`
`at node.js:902:3`

Any help is greatly aprreciated. :)

Thanks,
Aditya

**Comment by russellfei** [comment]
same error and `npm install express` won't work
