### ISSUE TITLE
module.js:333     throw err;

### ISSUE THREAD

**Issue by tohnperfect** [clementfarabet/gfx.js#41]
I got the following error when i tried $luajit -lgfx.start.

module.js:333
    throw err;
          ^
Error: Cannot find module 'pty.js'
    at Function.Module._resolveFilename (module.js:331:15)
    at Function.Module._load (module.js:273:25)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/home/localadmin/.gfx.js/lib/tty.js:17:11)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Module.require (module.js:357:17)

**Comment by soumith** [comment]
gfx is being depreceated because of such errors with pty.js and tty.js. those modules are no longer being maintained upstream and seem to be broken.

we are starting to use iTorch, or you can install https://github.com/szym/display which is a stripped down version of gfx.js which installs easily out of the box.

**Comment by tohnperfect** [comment]
OK. I am aiming to use iTorch as well.

Thank you, Soumith.

**Comment by lacker** [comment]
If gfx.js is no longer supported and it's better to use iTorch or display now, how about saying that in the readme?
